// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtA3VZBps6RzjXQmakoPaUXRadQ3X4oz0',
    appId: '1:952410601237:web:af31e90f81b30bcb729b1c',
    messagingSenderId: '952410601237',
    projectId: 'instagram-f0b81',
    authDomain: 'instagram-f0b81.firebaseapp.com',
    storageBucket: 'instagram-f0b81.appspot.com',
    measurementId: 'G-9QFYJS7S8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEQTYouFd2qYa7rVm153B34yVtwzWG378',
    appId: '1:952410601237:android:924bb9cdfd8fcbf7729b1c',
    messagingSenderId: '952410601237',
    projectId: 'instagram-f0b81',
    storageBucket: 'instagram-f0b81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx1c-oslxAt9TUSkxebnwuF9_bifeLyuc',
    appId: '1:952410601237:ios:29df818e04913472729b1c',
    messagingSenderId: '952410601237',
    projectId: 'instagram-f0b81',
    storageBucket: 'instagram-f0b81.appspot.com',
    iosClientId: '952410601237-jqbfch0aeuub06na8b9gl6ublhinrf9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx1c-oslxAt9TUSkxebnwuF9_bifeLyuc',
    appId: '1:952410601237:ios:29df818e04913472729b1c',
    messagingSenderId: '952410601237',
    projectId: 'instagram-f0b81',
    storageBucket: 'instagram-f0b81.appspot.com',
    iosClientId: '952410601237-jqbfch0aeuub06na8b9gl6ublhinrf9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
